create database practice;

use practice;

show databases;

CREATE TABLE STUDENTS (
SNO INT PRIMARY KEY AUTO_INCREMENT,
SNAME VARCHAR(20),
PLACE VARCHAR(20));

SHOW TABLES;

# ********** DDL COMMANDS ***************


INSERT INTO STUDENTS ( SNAME, PLACE) VALUES ( 'SREEJA', 'NELLORE');
INSERT INTO STUDENTS (SNAME ,PLACE ) VALUES ('TEJASWINI', 'KOTA'), ('DEEPIKA','PODALAKURU');
SELECT * FROM STUDENTS;
DESC STUDENTS;

ALTER TABLE STUDENTS MODIFY SNAME VARCHAR(30);

ALTER TABLE STUDENTS ADD FNAME VARCHAR(10) AFTER SNO;

ALTER TABLE STUDENTS DROP COLUMN FNAME;

CREATE TABLE SAI (NAME VARCHAR(20));
DROP TABLE SAI;

TRUNCATE STUDENTS;
ALTER TABLE STUDENTS RENAME SINFO;
SELECT * FROM SINFO;



# ********* DML COMMANDS ************

CREATE TABLE FPLACE (FNAME VARCHAR(20), PLACE VARCHAR(30));

INSERT  INTO FPLACE VALUES ( "TEJA", "KOTA"),("SREEJA" , "NELLORE");
SELECT * FROM FPLACE; 

UPDATE FPLACE SET FNAME ='SAI' WHERE PLACE='NELLORE';



